### ISSUE TITLE
V2 log list schema being introduced

### ISSUE THREAD

**Issue by mattmook** [Babylonpartners/certificate-transparency-android#1]
At some point a new v2 schema for the log list will be released.
https://groups.google.com/forum/?fromgroups=#!topic/certificate-transparency/zZwGExvQeiE

At such a time this library needs to update to use it.

**Comment by RJPercival** [comment]
Google's beta versions of this new log list can be found here: 
http://www.gstatic.com/ct/log_list/v2_beta/log_list.json (only logs accepted by Chrome)
http://www.gstatic.com/ct/log_list/v2_beta/all_logs_list.json (all known logs)

Apple's version of this new log list can be found here:
https://valid.apple.com/ct/log_list/current_log_list.json

**Comment by mattmook** [comment]
@RJPercival do you when this is likely to be adopted by Google? The latest version of the beta came out back in Jan.

I assume this will replace the file at https://www.gstatic.com/ct/log_list/log_list.json when that happens.

As an aside, although the library currently accesses Google's log_list.json file we are looking at moving this to our own file that we have more control over in the not so distant future. One of the reasons for us to do this is we are looking to reduce the chances of replay attacks with this data.

**Comment by mattmook** [comment]
Seems this has now been launched - https://groups.google.com/forum/#!topic/certificate-transparency/zZwGExvQeiE

Specifically, the following are now available:

https://www.gstatic.com/ct/log_list/v2/log_list_schema.json - the new JSON schema.
https://www.gstatic.com/ct/log_list/v2/all_logs_list.json - the log list containing all known Logs (past and present).
https://www.gstatic.com/ct/log_list/v2/log_list.json - the list of Logs that are currently compliance with Chrome's CT Log policy (or have been and were retires), and are included in Chrome.
https://www.gstatic.com/ct/log_list/v2/log_list.sig - Google's signature for log_list.json
https://www.gstatic.com/ct/log_list/v2/log_list_pubkey.pem - the public key required to verify log_list.sig

**Comment by mattmook** [comment]
Switched to v2 schema in v0.5.0
