### ISSUE TITLE
CT enablement causes failures for http traffic

### ISSUE THREAD

**Issue by yschimke** [Babylonpartners/certificate-transparency-android#11]
```
2019-06-08 11:30:02.028 3260-3741/com.okhttpandroidapp W/AndroidNetworkManager: ct: api.twitter.com Failure: No certificates
```

http vs https seems like a separate concern, e.g. HSTS.  Should the default be to allow http traffic still and skip the checks?

**Comment by mattmook** [comment]
Yes this should be allowed, the OkHttp interceptor is a little too aggressive here 😄
